#!/bin/bash
if [ ! $@ ]; then
name='broker-ins'
else
name=$@
fi
docker rmi `docker ps -aq -f name=$name`
set -a
source .env

docker run --rm \
--network zmqgh-network \
-e FILEQUEUE_DB_DIR=$FILEQUEUE_DB_DIR \
-e FILEQUEUE_MAX_BYTES_PER_FILE=$FILEQUEUE_MAX_BYTES_PER_FILE \
-e FILEQUEUE_MIN_MSG_SIZE=$FILEQUEUE_MIN_MSG_SIZE \
-e FILEQUEUE_MAX_MSG_SIZE=$FILEQUEUE_MAX_MSG_SIZE \
-e FILEQUEUE_SYNC_EVERY=$FILEQUEUE_SYNC_EVERY \
-e FILEQUEUE_SYNC_TIMEOUT=$FILEQUEUE_SYNC_TIMEOUT \
-e REQUEST_TIMEOUT=$REQUEST_TIMEOUT \
-e REQUEST_RETRIES=$REQUEST_RETRIES \
-e BROKER_DESTINATION_REQ_ENDPOINT=$BROKER_DESTINATION_REQ_ENDPOINT \
-e BROKER_REP_ENDPOINT=$BROKER_REP_ENDPOINT \
--name $name broker-img
